server:
  port: 9223

spring:
  application:
    name: seata-repository-service
  cloud:
    alibaba:
      seata:
        tx-service-group: oar_tx_group
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/db_repository
    username: root
    password: Rocky@nb



feign:
  hystrix:
    enabled: false
logging:
  level:
    io:
      seata: info
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: today.rocky.cloud.seata.repository.mapper